### ISSUE TITLE
Help on understanding information in intent_links

### ISSUE THREAD

**Issue by cedricbonhomme** [siis/primo#2]
Hello,

I am using PRIMO in order to generate a graph representing the relations between a set of Android applications.
The graph is represented in the GEXF format and I am using Gephi to make queries on it and to generate some graphs...

For the moment I only want to see if an application A has a link with an application B. I don't need for the moment to represent which intent of an application represents an external link.

I've mainly understand the structure of the data used by PRIMO. But still, I am not sure that my script is correct. Though, the graphs are pretty nice...

So, can you just review this little script:
https://gist.github.com/cedricbonhomme/8aaac623480912661ff29e4395bb5414/8419df94a092329a5960bb27cbf20dfd425a7bea

thanks a lot!

Cédric

**Comment by cedricbonhomme** [comment]
This is maybe a better solution:
https://gist.github.com/cedricbonhomme/8aaac623480912661ff29e4395bb5414/508dd3e9e1840019a21e2504bda7d4e9b6562388

**Comment by cedricbonhomme** [comment]
Hello @docteau , did you check if the approach seems to be valid?

**Comment by docteau** [comment]
Hi Cédric,

Sorry, I haven't had time to take a look yet as I've been traveling. I'll take a look as soon as I get some time.

Damien

**Comment by docteau** [comment]
Hi Cédric,

Yes, that looks good to me. Nice job!

Best,
Damien

**Comment by cedricbonhomme** [comment]
Hi Damien,

thank you for the confirmation! I am a little bit surprised ;-)
I'll be able to continue on that!

thanks!
